### ISSUE TITLE
error running docker-compose up

### ISSUE THREAD

**Issue by sela** [eko/docker-symfony#16] opened 2015-12-04 15:40 UTC
I get the following error

**e89a19c56178: Error pulling image (latest) from docker.io/willdurand/elk, Driver aufs failed to create image rootfs 6016c7ab9091a3333c335a505e5e60c022ad2296ab36c4db3bb51b59930f9f40: write /mnt/sda1/var/lib/docker/aufs/layers/6016c7ab9091a3333c335a505e5e60c022ad2296ab36c4db3bb51b59930f9f40: no space left on device4db3bb51b59930**

I got 39GB fee space on my HD so not sure why I get that error.

**Comment by RVN-BR** [comment] 2015-12-15 13:56
replace willdurand/elk with willdurand/docker-elk ?  I realized willdurand changed the package name (or maybe it was always like that) but anyways, there is not willdurand/elk

**Comment by sela** [comment] 2015-12-30 11:37
I changed the file docker-compose.yml but it seems that's not where I need to change it as then it doesn't work at all.

**Comment by eko** [comment] 2018-08-01 19:12
Hello,

Sorry but I can't reproduce this issue. I close this issue but feel free to reopen if there is any issue related to docker-symfony project.

Thank you

**Closed by eko** 2018-08-01 19:12 UTC
