### ISSUE TITLE
Problems with permissions inside a container

### ISSUE THREAD

**Issue by ltarasiewicz** [eko/docker-symfony#7] opened 2015-06-10 22:11 UTC
Hello,

I've followed the setup instructions and got all containers running as expected. However, when visiting `symfony.dev` I see a blank page. When I inspected symfony error log I saw this message:

```
thrown in /var/www/symfony/app/bootstrap.php.cache on line 2659" while reading response header from upstream, client: 172.17.42.1, server: symfony.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://172.17.0.19:9000", host: "symfony.dev"
2015/06/10 22:05:02 [error] 5#0: *22 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to write in the logs directory (/var/www/symfony/app/logs)
' in /var/www/symfony/app/bootstrap.php.cache:2659
Stack trace:
#0 /var/www/symfony/app/bootstrap.php.cache(2617): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/symfony/app/bootstrap.php.cache(2396): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/symfony/app/bootstrap.php.cache(2427): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/symfony/web/app.php(28): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
```

I guess this has to do with permissions inside a container. How could I solve this problem?

**Comment by B-Galati** [comment] 2015-06-11 06:45
Hello,

It is your Symfony configuration which encounters a problem here.
Let's have a look to [Symfony Doc](http://symfony.com/doc/current/book/installation.html#checking-symfony-application-configuration-and-setup) and read the part called *Setting up Permissions*.

**Comment by 3lect** [comment] 2015-09-27 00:24
HI
I have got this issue too.
For resolve it, my system doesn't support chmod +a :
apt-get install acl
$ HTTPDUSER=`ps aux | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\  -f1`
$ sudo setfacl -R -m u:"$HTTPDUSER":rwX -m u:`whoami`:rwX app/cache app/logs
$ sudo setfacl -dR -m u:"$HTTPDUSER":rwX -m u:`whoami`:rwX app/cache app/logs

AND

$ sudo setfacl -R -m u:"$HTTPDUSER":rwX -m u:`whoami`:rwX logs/symfony
$ sudo setfacl -dR -m u:"$HTTPDUSER":rwX -m u:`whoami`:rwX logs/symfony

where for me logs/symfony is : /home/docker/docker-symfony/logs/symfony

**Comment by taher-mosbah** [comment] 2015-09-28 15:38
Hello,
@3lect, for me  $HTTPDUSER is empty and I think that's normal because nginx and httpd are not running, when exactly do you call your script please ?

**Comment by B-Galati** [comment] 2015-09-29 10:57
@taher-mosbah Start containers with `docker-compose up` then run the script above

**Comment by taher-mosbah** [comment] 2015-09-29 11:57
Thanks @B-Galati, the problem is than I'm deploying on Elastic Beanstalk and can't run any commands after deployment ..

**Comment by eko** [comment] 2018-08-01 19:16
Hello,

Closing this issue has it is related to setting permissions on your environment.

Thank you

**Closed by eko** 2018-08-01 19:16 UTC
