### ISSUE TITLE
Nginx refuses to connect

### ISSUE THREAD

**Issue by brud** [eko/docker-symfony#47] opened 2016-10-08 01:13 UTC
Hi, I make `docker-compose up` succesfull (only logstash can't find the config - I'd commented it for now), then I add `127.0.0.1 symfony.dev` into my hosts file, open in browser `http://symfony.dev` and get `net::ERR_CONNECTION_REFUSED`

**Comment by rivetmichael** [comment] 2016-10-18 08:06
Hi, 

What does `docker-compose ps` command returns ?

**Comment by sanket2385** [comment] 2016-10-21 19:33
<img width="795" alt="screen shot 2016-10-21 at 20 33 06" src="https://cloud.githubusercontent.com/assets/185229/19609183/a447a274-97cd-11e6-9f4e-afeaa83c4a10.png">

**Comment by omahm** [comment] 2017-04-22 18:12
If you're using OSX you'll need to make an entry in your /etc/hosts with: 0.0.0.0 symfony.dev

**Comment by eko** [comment] 2018-08-01 18:56
Hello,

I can't reproduce this issue.

Closing this issue now but feel free to reopen if it is still relevent.

Thank you

**Closed by eko** 2018-08-01 18:56 UTC
