### ISSUE TITLE
MSSQL Server configuration

### ISSUE THREAD

**Issue by bronkitoide** [eko/docker-symfony#88] opened 2018-08-24 07:48 UTC
Hello, I have a problem with configuring the MSSQL Server as the database. 
Could somebody explain me how to prepare the configuration? I receive 

`In SQLSrvConnection.php line 67:`                                        
`Attempted to call function "sqlsrv_configure" from the global namespace.  `
                                                                           
error.

En .env I have:

`DATABASE_URL=sqlsrv://SA:SA_Password@db:1433/database_name`

In services.yaml:

`parameters:`
`    locale: 'en'`
`    DATABASE_HOST: db`
`    DATABASE_USER: SA`
`    DATABASE_PASSWORD:`

In doctrine.yaml:

`parameters:`
`    env(DATABASE_URL): 'sqlsrv://SA:@db:1433/database_name'`
`    database_user: SA`
`    database_password: SA_Password`
` `
`doctrine:`
`    dbal:`
`        # configure these for your database server`
`        driver: 'sqlsrv'`
`        # server_version: '5.7'`
`        # scharset: utf8mb4`
`        default_table_options:`
`            charset: utf8mb4`
`            collate: utf8mb4_unicode_ci`
` `
`        url: '%env(resolve:DATABASE_URL)%'`

Why can't I connect to the database while doing:
`docker exec 430129ed06e8 bin/console doctrine:database:create` ?

In the Dockerfile I added 2 new extensions:
`  php7-sqlsrv \` 
` php7-pdo_sqlsrv \` 

And in docker-compose.yml
`   db:`
`        image: microsoft/mssql-server-linux:2017-latest`
`        ports:`
`            - "1433:1433"`
`        environment:`
`            SA_PASSWORD: "SA_Password"`
`            ACCEPT_EULA: "Y"`

**Comment by eko** [comment] 2018-08-25 12:58
Hello @bronkitoide,

On this project, we are using Linux (Alpine distribution) in order to run PHP container but it appears that the `pdo_sqlsrv` PHP's extension is only available on Windows so it might be the cause of your issue:

> The PDO_SQLSRV extension is only compatible with PHP running on Windows. For Linux, see ODBC and » Microsoft's SQL Server ODBC Driver for Linux.

See: http://php.net/manual/en/ref.pdo-sqlsrv.php

To resolve your issue, you have to install the Microsoft's ODBC driver for Linux. You have to update container with the things contained on this blog post: https://breeto.id.au/2017/05/docker-alpine-linux-php-sql-server/

I hope it helps. Please close the issue once it's resolved on your side.

Thank you

**Comment by bronkitoide** [comment] 2018-09-23 10:32
Thank you very much!

**Closed** 2018-09-23 10:31 UTC
