### ISSUE TITLE
ELK crash logstash after spawning and exited

### ISSUE THREAD

**Issue by anboo** [eko/docker-symfony#54] opened 2017-03-30 08:18 UTC
> elk_1   | 2017-03-30 08:15:29,783 CRIT Supervisor running as root (no user in config file)
> elk_1   | 2017-03-30 08:15:29,784 WARN Included extra file "/etc/supervisor/conf.d/kibana.conf" during parsing
> elk_1   | 2017-03-30 08:15:29,784 WARN Included extra file "/etc/supervisor/conf.d/logstash.conf" during parsing
> elk_1   | 2017-03-30 08:15:29,784 WARN Included extra file "/etc/supervisor/conf.d/elasticsearch.conf" during parsing
> elk_1   | 2017-03-30 08:15:29,796 INFO RPC interface 'supervisor' initialized
> elk_1   | 2017-03-30 08:15:29,796 CRIT Server 'unix_http_server' running without any HTTP authentication checking
> elk_1   | 2017-03-30 08:15:29,797 INFO supervisord started with pid 1
> elk_1   | 2017-03-30 08:15:30,798 INFO spawned: 'elasticsearch' with pid 7
> elk_1   | 2017-03-30 08:15:30,799 INFO spawned: 'logstash' with pid 8
> elk_1   | 2017-03-30 08:15:30,800 INFO spawned: 'kibana' with pid 9
> elk_1   | 2017-03-30 08:15:32,468 INFO success: elasticsearch entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> elk_1   | 2017-03-30 08:15:32,468 INFO success: logstash entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> elk_1   | 2017-03-30 08:15:32,468 INFO success: kibana entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> elk_1   | 2017-03-30 08:15:49,745 INFO exited: logstash (exit status 1; not expected)
> elk_1   | 2017-03-30 08:15:50,749 INFO spawned: 'logstash' with pid 83
> elk_1   | 2017-03-30 08:15:51,750 INFO success: logstash entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> elk_1   | 2017-03-30 08:15:59,759 INFO exited: logstash (exit status 1; not expected)
> elk_1   | 2017-03-30 08:16:00,761 INFO spawned: 'logstash' with pid 113
> elk_1   | 2017-03-30 08:16:01,767 INFO success: logstash entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> elk_1   | 2017-03-30 08:16:08,982 INFO exited: logstash (exit status 1; not expected)
> elk_1   | 2017-03-30 08:16:09,984 INFO spawned: 'logstash' with pid 142
> elk_1   | 2017-03-30 08:16:10,986 INFO success: logstash entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> elk_1   | 2017-03-30 08:16:17,975 INFO exited: logstash (exit status 1; not expected)
> elk_1   | 2017-03-30 08:16:18,976 INFO spawned: 'logstash' with pid 172
> elk_1   | 2017-03-30 08:16:19,979 INFO success: logstash entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> elk_1   | 2017-03-30 08:16:26,884 INFO exited: logstash (exit status 1; not expected)
> elk_1   | 2017-03-30 08:16:27,886 INFO spawned: 'logstash' with pid 201
> elk_1   | 2017-03-30 08:16:28,887 INFO success: logstash entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> elk_1   | 2017-03-30 08:16:35,669 INFO exited: logstash (exit status 1; not expected)
> elk_1   | 2017-03-30 08:16:36,671 INFO spawned: 'logstash' with pid 230
> elk_1   | 2017-03-30 08:16:37,672 INFO success: logstash entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> elk_1   | 2017-03-30 08:16:44,391 INFO exited: logstash (exit status 1; not expected)
> elk_1   | 2017-03-30 08:16:45,392 INFO spawned: 'logstash' with pid 259
> elk_1   | 2017-03-30 08:16:46,394 INFO success: logstash entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> elk_1   | 2017-03-30 08:16:53,147 INFO exited: logstash (exit status 1; not expected)
> elk_1   | 2017-03-30 08:16:54,149 INFO spawned: 'logstash' with pid 288
> elk_1   | 2017-03-30 08:16:55,150 INFO success: logstash entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> elk_1   | 2017-03-30 08:17:01,896 INFO exited: logstash (exit status 1; not expected)
> elk_1   | 2017-03-30 08:17:02,898 INFO spawned: 'logstash' with pid 317
> elk_1   | 2017-03-30 08:17:03,900 INFO success: logstash entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> elk_1   | 2017-03-30 08:17:10,547 INFO exited: logstash (exit status 1; not expected)
> elk_1   | 2017-03-30 08:17:11,549 INFO spawned: 'logstash' with pid 346
> elk_1   | 2017-03-30 08:17:12,550 INFO success: logstash entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> elk_1   | 2017-03-30 08:17:19,130 INFO exited: logstash (exit status 1; not expected)
> elk_1   | 2017-03-30 08:17:20,132 INFO spawned: 'logstash' with pid 375
> elk_1   | 2017-03-30 08:17:21,136 INFO success: logstash entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> elk_1   | 2017-03-30 08:17:28,040 INFO exited: logstash (exit status 1; not expected)
> elk_1   | 2017-03-30 08:17:29,042 INFO spawned: 'logstash' with pid 404
> elk_1   | 2017-03-30 08:17:30,047 INFO success: logstash entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> elk_1   | 2017-03-30 08:17:36,991 INFO exited: logstash (exit status 1; not expected)
> elk_1   | 2017-03-30 08:17:37,993 INFO spawned: 'logstash' with pid 433
> elk_1   | 2017-03-30 08:17:38,997 INFO success: logstash entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> elk_1   | 2017-03-30 08:17:45,766 INFO exited: logstash (exit status 1; not expected)
> elk_1   | 2017-03-30 08:17:46,768 INFO spawned: 'logstash' with pid 462
> elk_1   | 2017-03-30 08:17:47,771 INFO success: logstash entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> elk_1   | 2017-03-30 08:17:56,453 INFO exited: logstash (exit status 1; not expected)
> elk_1   | 2017-03-30 08:17:57,455 INFO spawned: 'logstash' with pid 491
> elk_1   | 2017-03-30 08:17:58,457 INFO success: logstash entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> elk_1   | 2017-03-30 08:18:05,627 INFO exited: logstash (exit status 1; not expected)
> elk_1   | 2017-03-30 08:18:06,629 INFO spawned: 'logstash' with pid 520
> elk_1   | 2017-03-30 08:18:07,631 INFO success: logstash entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> elk_1   | 2017-03-30 08:18:14,686 INFO exited: logstash (exit status 1; not expected)
> elk_1   | 2017-03-30 08:18:15,688 INFO spawned: 'logstash' with pid 549
>

**Comment by eko** [comment] 2018-08-01 18:51
Hello,

I am sorry but I cannot reproduce this issue. Do you have enough memory to launch the different containers?

Closing this issue as anyone else has this issue. Feel free to re-open if it is still relevent.

Thank you

**Closed by eko** 2018-08-01 18:51 UTC

**Comment by Liombe** [comment] 2018-10-10 20:56
Hello, I have the same problem and have no logs to hint on the problem. Could you help me ?

Windows 10 Family x64
Docker Toolbox v18.06.1-ce

> 2018-10-10T20:33:45.040281Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using this option as it' is deprecated and will be removed in a future release.
db_1     | 2018-10-10T20:33:45.040395Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.12) starting as process 1
db_1     | mbind: Operation not permitted
db_1     | 2018-10-10T20:33:49.373593Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
db_1     | 2018-10-10T20:33:49.462485Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
db_1     | 2018-10-10T20:33:49.793959Z 0 [Warning] [MY-010315] [Server] 'user' entry 'mysql.infoschema@localhost' ignored in --skip-name-resolve mode.
db_1     | 2018-10-10T20:33:49.794640Z 0 [Warning] [MY-010315] [Server] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1     | 2018-10-10T20:33:49.795140Z 0 [Warning] [MY-010315] [Server] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1     | 2018-10-10T20:33:49.795536Z 0 [Warning] [MY-010315] [Server] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
db_1     | 2018-10-10T20:33:49.796037Z 0 [Warning] [MY-010323] [Server] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1     | 2018-10-10T20:33:49.796382Z 0 [Warning] [MY-010323] [Server] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1     | 2018-10-10T20:33:49.796825Z 0 [Warning] [MY-010311] [Server] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
db_1     | 2018-10-10T20:33:50.239334Z 0 [Warning] [MY-010330] [Server] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
db_1     | 2018-10-10T20:33:50.239807Z 0 [Warning] [MY-010330] [Server] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
elk_1    | 2018-10-10 20:33:50,471 CRIT Supervisor running as root (no user in config file)
elk_1    | 2018-10-10 20:33:50,471 WARN Included extra file "/etc/supervisor/conf.d/kibana.conf" during parsing
elk_1    | 2018-10-10 20:33:50,471 WARN Included extra file "/etc/supervisor/conf.d/logstash.conf" during parsing
elk_1    | 2018-10-10 20:33:50,472 WARN Included extra file "/etc/supervisor/conf.d/elasticsearch.conf" during parsing
elk_1    | 2018-10-10 20:33:50,485 INFO RPC interface 'supervisor' initialized
elk_1    | 2018-10-10 20:33:50,486 CRIT Server 'unix_http_server' running without any HTTP authentication checking
elk_1    | 2018-10-10 20:33:50,487 INFO supervisord started with pid 1
elk_1    | 2018-10-10 20:33:51,493 INFO spawned: 'elasticsearch' with pid 8
elk_1    | 2018-10-10 20:33:51,501 INFO spawned: 'logstash' with pid 9
elk_1    | 2018-10-10 20:33:51,516 INFO spawned: 'kibana' with pid 10
elk_1    | 2018-10-10 20:33:52,560 INFO success: elasticsearch entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
elk_1    | 2018-10-10 20:33:52,561 INFO success: logstash entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
elk_1    | 2018-10-10 20:33:52,561 INFO success: kibana entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
elk_1    | 2018-10-10 20:34:08,887 INFO exited: logstash (exit status 1; not expected)
elk_1    | 2018-10-10 20:34:09,913 INFO spawned: 'logstash' with pid 84
elk_1    | 2018-10-10 20:34:10,918 INFO success: logstash entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
elk_1    | 2018-10-10 20:34:20,683 INFO exited: logstash (exit status 1; not expected)
elk_1    | 2018-10-10 20:34:21,688 INFO spawned: 'logstash' with pid 114
elk_1    | 2018-10-10 20:34:22,692 INFO success: logstash entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
elk_1    | 2018-10-10 20:34:31,621 INFO exited: logstash (exit status 1; not expected)
elk_1    | 2018-10-10 20:34:32,627 INFO spawned: 'logstash' with pid 143
elk_1    | 2018-10-10 20:34:33,630 INFO success: logstash entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
elk_1    | 2018-10-10 20:34:43,051 INFO exited: logstash (exit status 1; not expected)
elk_1    | 2018-10-10 20:34:44,055 INFO spawned: 'logstash' with pid 173
elk_1    | 2018-10-10 20:34:45,059 INFO success: logstash entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
elk_1    | 2018-10-10 20:34:52,960 INFO exited: logstash (exit status 1; not expected)

**Comment by alfonsodev** [comment] 2018-10-30 17:14
I do have exactly the same problem, do you know how to get a more descriptive error message ?

**Comment by alfonsodev** [comment] 2018-10-30 17:38
I've found a posible reason looking into the log file 

`/var/log/logstash/stdout.log` 

```
  pattern %{NGINXACCESS} not defined
```

**Comment by okwinza** [comment] 2018-12-23 21:35
Had the same issue, specifying `patterns_dir => ["/etc/logstash/patterns"]` solved it.
In that case, `./elk/logstash/patterns:/opt/logstash/patterns:cached` line could also be removed from docker-compose.
